# Generated by Django 4.2.7 on 2026-01-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_match_matchseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, default='A', max_length=10, null=True),
        ),
    ]
