# Generated by Django 4.2.7 on 2026-01-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
