# Generated by Django 4.2.7 on 2026-01-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_team_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
