# Generated by Django 4.2.7 on 2026-01-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_create_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
